name: danesanders
favicon: null
layout_spectrum: 0.9989293050020933
typography_spectrum: 0.9902338176034391
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-60100244
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5933474288322031
purpose: []
